# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone:

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Glu # the main title

tagline: The Glu Programming Language # it will display as the sub-title

description: >- # used by seo meta and the atom feed
  The Glu Programming Language Organization.

# Fill in the protocol & hostname for your site.
# e.g. 'https://username.github.io', note that it does not end with a '/'.
url: ""

github:
  username: glu-lang

social:
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Glu Organisation
  links:
    - https://github.com/glu-lang

# the avatar on sidebar, support local or CORS resources
avatar: assets/img/favicons/apple-touch-icon.png

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  provider: giscus
  giscus:
    repo: glu-lang/glu-book
    repo_id: R_kgDOMQdjkw
    category: Discuss The Book
    category_id: DIC_kwDOMQdjk84CghFG

pwa:
  enabled: true # the option for PWA feature (installable)
  cache:
    enabled: true # the option for PWA offline cache
    # Paths defined here will be excluded from the PWA cache.
    # Usually its value is the `baseurl` of another website that
    # shares the same domain name as the current website.

paginate: 10

# The base URL of your site
baseurl: ""

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order
  docs:
    output: true
    order:
      - hello_world.md
      - constants_and_variables.md
      - use_functions.md
      - comments.md
      - control_flow.md
      - memory_management.md
      - structs.md
      - enums.md
      - typealiases.md
      - operators_overload.md
      - overloading_functions.md
      - templating_functions.md
      - templating_structures.md
      - importing_cpp.md
      - exporting_cpp.md
      - keywords.md
      - operators_and_symbols.md
  refs:
    output: true
    order:
      - compiler_architecture.md
      - bnf.md

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: ""
      type: docs
    values:
      layout: post
      comments: true
      toc: true # Display TOC column in posts.
      permalink: /:title/
  - scope:
      path: ""
      type: refs
    values:
      layout: post
      comments: true
      toc: true # Display TOC column in posts.
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
